-- CreateEnum
CREATE TYPE "AssignmentKind" AS ENUM ('ARBEIT', 'BESICHTIGUNG', 'AUFMASS', 'MATERIAL_BESTELLEN', 'MATERIAL_ANLIEFERUNG', 'ABNAHME', 'BESPRECHUNG', 'NACHARBEIT', 'SONSTIGES');

-- AlterTable
ALTER TABLE "assignments" ADD COLUMN     "kind" "AssignmentKind" NOT NULL DEFAULT 'ARBEIT',
ADD COLUMN     "tasks" TEXT[] DEFAULT ARRAY[]::TEXT[];
